### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by oberluz** [feranick/TFlite-builds#1]
Hi @feranick 

I've tried building it as per the instructions but I get build failures. Not sure if there is something missing in the instructions.

Tried ubuntu 22.04 with python 3.10 / 3.11, both native and aarch64. I always get a fatal error: Killed signal terminated program cc1plus message.

Also, when using python 3.11 I had to not include the line for externally managed as it didn't exist in the container.

Attaching the log in case you can spot any issues.

[build.log](https://github.com/feranick/TFlite-builds/files/14357976/build.log)
[git_info.txt](https://github.com/feranick/TFlite-builds/files/14358034/git_info.txt)

**Comment by feranick** [comment]
Hi Paul,

It seems you are running out of resources (RAM, especially). Regardless of the method used (docker, native, etc), compilation is VERY RAM intensive (I am running your configuration now, it's using 22GB RAM - the max I have on this system - and 4GB/swap). If your swap is fixed (i.e. cannot be dynamically extended), it may lead to the failure. 

I checked whether they use something like `-j 4` for compilation (as that increases resources use), but they don't. That said, you can try to explicitly restrict the number of jobs by changing line 126 in `tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh` from:

```
cmake --build . --verbose -j ${BUILD_NUM_JOBS} -t _pywrap_tensorflow_interpreter_wrapper
```
to:
```
cmake --build . --verbose -j 1 -t _pywrap_tensorflow_interpreter_wrapper
```

Not sure it will help, but may be something to try.
Please let me know if this helps.

**Comment by feranick** [comment]
If you have a configuration that is not covered by the provided builds in this repo, please let me know and I'll try to provide them here as well.

**Comment by feranick** [comment]
I am running a `-j 1` compilation run and while significantly slower, it maintains RAM at decent levels. You may be able to play with the -j value to speed it up a bit. The point is, the original code is supposed to have the `${BUILD_NUM_JOBS}` variable set, but it's actually not - anywhere - leaving the compiler to use as many processes as it can, blowing RAM usage under proportion.

For context a `-j 1` uses ~11GB RAM and no swap. With `-j 4` it is a bit higher but still very manageable and notably faster.

**Comment by feranick** [comment]
I filed a bug report to TF:

https://github.com/tensorflow/tensorflow/issues/63018

**Comment by oberluz** [comment]
Hi,

I set it to -j4 and ot worked well and reasonably fast. I think you can set
it in the environment. I'll try and let you know of I succeed.

Thanks
Paul

**Comment by feranick** [comment]
Thanks, Paul. I think it's safe to use even higher numbers. Basically you can try and up it until it crashes. This of course if speed of compilationis crucial to you.

I won't recommend changing it by default, as it's blazing fast if you have the resources...

Thanks for your help.
