### ISSUE TITLE
MacOS wheel for 2.17

### ISSUE THREAD

**Issue by psalaberria002** [feranick/TFlite-builds#3]
Hei!

Thanks for the efforts on making wheels for various platforms and new Python versions.

Any plans for uploading a wheel for MacOS?

**Comment by feranick** [comment]
2.17.0-rc0 (release candidates) now available for MacOS (Intel only, I don't have Silicon). Stable will be released as well.

If you follow the instructions for Native builds with Bazel, you can asily compile it yourself.

**Comment by feranick** [comment]
Wheels for v2.17.0 are now available.
