### ISSUE TITLE
Missing Python 3.11 on Linux x86_64?

### ISSUE THREAD

**Issue by brunokc** [feranick/TFlite-builds#4]
Hello, 

Firstly, thank you very much for doing this. I appreciate having these ready-to-go packages for my system. 

Is it me or are you missing a whl for Python 3.11 for Linux x86_64? I found one for .39, 3.10 and 3.12 but couldn't find the one for 3.11.

Thanks!

**Comment by feranick** [comment]
Good catch! Sorry it must have been lost during the upload. It's there now. 

Thanks!

**Comment by brunokc** [comment]
Much appreciate the quick turnaround!
